#!/bin/sh

# https://unix.stackexchange.com/a/293477
finddevopsy() {
  # from: https://www.npmjs.com/package/find-config#algorithm
  # 1. If X/file.ext exists and is a regular file, return it. STOP
  # 2. If X has a parent directory, change X to parent. GO TO 1
  # 3. Return NULL.

  if [ -d "$1" ]; then
    printf '%s' "${PWD%/}/$1"
  elif [ "$PWD" = / ]; then
    false
  else
    # a subshell so that we don't affect the caller's $PWD
    (cd .. && finddevopsy "$1")
  fi
}

DEVOPSY_PROJECT_DIR=$(finddevopsy .devopsy)

if [ -z $DEVOPSY_PROJECT_DIR ]; then
  echo -e "\033[0;31m.devopsy/ not found anywhere up this project.\033[0m"
  exit 100
fi

if [ ! -f $DEVOPSY_PROJECT_DIR/compose.yaml ]; then
  echo -e "\033[0;31m$DEVOPSY_PROJECT_DIR/compose.yml not found in the current directory.\033[0m"
  exit 1
fi
compose_files="$compose_files -f $DEVOPSY_PROJECT_DIR/compose.yaml"
if [ -f $DEVOPSY_PROJECT_DIR/compose.override.yaml ]; then
  compose_files="$compose_files -f $DEVOPSY_PROJECT_DIR/compose.override.yaml"
fi

if [ "$DEVOPSY_CLI_COMMAND" != "$1" ] && [ -x "$DEVOPSY_PROJECT_DIR/commands/$1" ]; then
  cmd=$1
  shift
  export DEVOPSY_PROJECT_DIR
  export DEVOPSY_CLI_COMMAND=$cmd
  $DEVOPSY_PROJECT_DIR/commands/$cmd "$@"
else
  docker compose $compose_files "$@"
fi
